name = "Steel Dominion [World]"
author = "Steel Dominion Community Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50e5f7ff37d2a11c89374589d1bbc6ff9bf766c807be45e8295f1fc8e7b09b41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
