name = "Steel Dominion [World]"
author = "Steel Dominion Community Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cabeb131b142f44cddd93ec5d2cbc7d9b37b7ebbbda631c663bba6a0e494a8b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
