name = "Steel Dominion [World]"
author = "Steel Dominion Community Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e62dd8285ce06f519eb97d2e7f1c520ef5e63c79f84e975b9dfc5f7fc0e4329"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
