name = "Steel Dominion [World]"
author = "Steel Dominion Community Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f353e255bb846c58acdccd0f7471ae435c1dbdac9efc479afe302f73730ea46b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
