name = "Steel Dominion [World]"
author = "Steel Dominion Community Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de2d0518f82cc21b875a7c10a6807465798bc07b6395e59ce0cf13c00e30940d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
