name = "Steel Dominion [World]"
author = "Steel Dominion Community Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "658f7f3826ec5aac91d0046d3916a0598e58216f8eaeec28d05ecebbdde56a27"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
