name = "Steel Dominion [World]"
author = "Steel Dominion Community Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "315fffa314c305f02db15301bf41b6269ab9f199220436fb3aaaf117089cd18d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
