name = "Steel Dominion [World]"
author = "Steel Dominion Community Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a29eb4a30f8ca1530735b893f36d1d545016b602cc9b653d4021b129ef10f958"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
