name = "Steel Dominion [World]"
author = "Steel Dominion Community Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7900cb771533e3a0cd864814ab74d6d567def07e35e723b12fd0f834990be7fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
